### ISSUE TITLE
error 'valid_format' undeclared in reader.c 715

### ISSUE THREAD

**Issue by jtickle** [xflouris/PEAR#22]
I didn't think this a big enough change to go to the trouble of a pull request, but I was unable to build b179da1e368950f153a5fbca586f72c514444157.  It appears to only be a problem if you are missing zlib.

The ifdef in reader.c on line 685 declares valid_format only if bzlib is present.  Then, down in line 715, valid_format is set only if neither bzlib nor zlib are present.  I fixed this locally by moving 'int valid_format=0' outside the ifdef.

Additionally, it seems that the ifdef on 685 may be inconsistent - the rest are checking for both zlib and bzlib.

I should probably have bzlib headers installed anyway but I figured you'd want to know.

**Comment by xflouris** [comment]
Thanks for the bug report Jeff. Indeed valid_format should be outside the ifdef. I've updated that now.
Otherwise, the ifdef should be okay; 'error' is declared only for bzlib as it is only used in BZ2_bzRead.
