### ISSUE TITLE
unassembled reverse reads file

### ISSUE THREAD

**Issue by sghignone** [xflouris/PEAR#32]
Hello, 
this is actually not an issue, but simply a question regarding the output file.
The sequences in:
`output_prefix.unassembled.reverse.fastq - unassembled reverse reads`
have  been reversed and complemented?
It might be useful to add an option for leaving them in original direction.
Thanks
s.

**Comment by tseemann** [comment]
+1 nice pickup!

**Comment by xflouris** [comment]
thanks for the suggestion. 

For now, as Jimmy O'Donnell suggested in the mailing list you can use [seqtk](https://github.com/lh3/seqtk) for reversing the reads. But I will add an option for keeping the original direction.

**Comment by tseemann** [comment]
@sghignone I think this explains why i was having trouble passing this data onto Spades assembler! 
I was giving the assembled reads as SE reads `-s`, and the unassembled reads as `-1` and `-2` but of course `-2` I now realise was not in the correct orientation.

**Comment by xflouris** [comment]
Added a -k option that keeps the reads in their original direction (no reverse-complementing) when printing them in the unassembled/discarded files.
